defaults_developmet: &defaults_developmet
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  database: db/development.sqlite3
  <<: *defaults_developmet

production:
  database: db/blog.sqlite3
  <<: *defaults_developmet